# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 青椒
subtitle: ''
description: "一蓑烟雨任平生"
keywords:
author: Zhch's Blog
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next   # landscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/zhchhe/zhchhe.github.io.git
  branch: main




# hexo-word-counter插件
symbols_count_time:
  # NexT 显示帖子元数据中的帖子词数
  symbols: true
  # NexT 在帖子元数据显示帖子的估计阅读时间
  time: true
  # NexT 在页脚部分显示所有帖子的单词数
  total_symbols: true
  # NexT 在页脚部分显示所有帖子的预计阅读时间
  total_time: true
  # 平均字长（字中的字符数）
  awl: 4
  # 每分钟的平均字数
  wpm: 80




# 此插件发出命令 pandoc 来调用 pandoc
pandoc:
  pandoc_path: C:/Program Files/Pandoc/pandoc.exe
  args:
    - '-f'
    - 'markdown'
    - '-t'
    - 'html'
    - '--mathjax'

# https://theme-next.js.org/docs/third-party-services/math-equations.html
# mathjax数学公式渲染
math:
  # Default (false)将根据需要加载mathjax / katex脚本。
  # 也就是说，它只渲染那些有' mathjax: true '在 little-form 的页面。
  # 如果将其设置为true，它将每页加载mathjax / katex脚本。
  every_page: false

  mathjax:
    enable: true
    # Available values: none | ams | all
    tags: ams

# https://theme-next.js.org/docs/third-party-services/comments.html
# 多评论系统支持
comments:
  # Available values: tabs | buttons
  style: tabs
  # 选择默认显示的评论系统
  # Available values: disqus | disqusjs | changyan | livere | gitalk | utterances | isso
  active:
  # 设置`true`表示记住访问者选择的评论系统
  storage: true
  # 延迟加载所有评论系统。
  lazyload: false


# Gitalk 评论插件
# For more information: https://gitalk.github.io
gitalk:
  enable: true
  github_id: zhchhe # GitHub repo owner
  repo: Gitalk-Blog-Talk # Repository name to store issues
  client_id: 6df1351813265c566a9a # GitHub Application Client ID
  client_secret: e5d4b3efac919636edce77be1f3811ee1b0acde9 # GitHub Application Client Secret
  admin_user: zhchhe # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# 主题备用配置
theme_config:

  # next主题
  scheme: Gemini

  # 黑暗mod false true
  darkmode: true

  # 侧边栏头像
  avatar:
    # 替换默认图片并在此处设置url
    url: https://github.com/zhchhe/image-bed/raw/fb4abe7d1106dda7e5256f6b31061a40707e717a/%E5%8D%9A%E5%AE%A2%E5%9B%BE%E7%89%87/%E5%A4%B4%E5%83%8F.jpg
    # 如果为true，头像将显示为圆形
    rounded: false

  # next菜单自定义页面
  menu:
    # 首页
    home: / || fa fa-home
    # 归档
    archives: /archives/ || fa fa-archive
    #标签
    tags: /tags/ || fa fa-tags
    #分类
    categories: /categories/ || fa fa-th
    # 关于
    about: /about/ || fa fa-user
    # 自定义
    #custom-name: /custom-name/ || fa fa-heart
    # 日程表
    #schedule: /schedule/ || fa fa-calendar
    # 站点地图
    #sitemap: /sitemap.xml || fa fa-sitemap
    # 公益404
    #commonweal: /404/ || fa fa-heartbeat

  # 预连接（preconnect）资源提示，以在网页加载过程中提前建立与字体和插件来源的连接。
  preconnect: true


  # 设置代码块高亮样式
  # 参考网址：https://theme-next.js.org/highlight/
  codeblock:
    # Code Highlight theme
    # All available themes: https://theme-next.js.org/highlight/
    theme:
      light: base16/windows-10
      dark: base16/windows-10
      #dark: stackoverflow-dark
    prism:
      light: base16/windows-10
      dark: base16/windows-10
    # 在代码块上添加复制按钮
    copy_button:
      enable: true
      # Available values: default | flat | mac
      style:

  #返回顶部按钮
  back2top:
    # 显示 Back to top 按钮
    enable: true
    # 将按钮放在边栏中
    sidebar: true
    # 在 Back to top 按钮中显示滚动百分比标签
    scrollpercent: true

  # 页面滚动阅读进度指示器
  reading_progress:
    enable: true
    # 可用的值: left | right
    start_at: left
    # 可用的值: top | bottom
    position: top
    reversed: false
    color: "#4dd17c"
    height: 4px

  # 右上角提供GitHub横幅
  github_banner:
    enable: true
    permalink: https://github.com/zhchhe

  font:
    enable: false

    # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
    host:

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: x.x`. Use `em` as unit. Default: 1 (16px)

    # Global font settings used for all elements inside <body>.
    global:
      external: true
      family: LXGW WenKai
      size:

    # Font settings for site title (.site-title).
    title:
      external: true
      family: LXGW WenKai
      size:

    # Font settings for headlines (<h1> to <h6>).
    headings:
      external: true
      family: LXGW WenKai
      size:

    # Font settings for posts (.post-body).
    posts:
      external: true
      family: LXGW WenKai

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: LXGW WenKai


  # 社交链接
  # 用法: `Key: permalink || icon`
  # Key 是显示给最终用户的链接标签
  # `||` 分隔符之前的值是目标永久链接，`||` 分隔符之后的值是 Font Awesome 图标的名称
  social:
    GitHub: https://github.com/zhchhe || fab fa-github
    #E-Mail: mailto:yourname@gmail.com || fa fa-envelope
    #Weibo: https://weibo.com/yourname || fab fa-weibo
    #Twitter: https://twitter.com/yourname || fab fa-twitter
    #FB Page: https://www.facebook.com/yourname || fab fa-facebook
    #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
    #YouTube: https://youtube.com/yourname || fab fa-youtube
    #Instagram: https://instagram.com/yourname || fab fa-instagram
    #Skype: skype:yourname?call|chat || fab fa-skype

  # 博客卷
  links_settings:
    icon: fa fa-globe
    # 正确的值: block | inline
    layout: inline  
  # 链接
  links:
    别人的网站: https://blog.imkasen.com/

